blogs/urls.py
from django.urls import path

from blogs.views import BlogListView, BlogDetailView

app_name = 'blogs'

urlpatterns = [
    path('', BlogListView.as_view(), name='list'),
    path('detail<int:pk>/', BlogDetailView.as_view(), name='detail'),
]

conf/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
    path('blogs/', include('blogs.urls', namespace='blogs')),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blogs/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class AuthorModel(models.Model):
    name = models.CharField(max_length=128, verbose_name=_('name'))
    image = models.ImageField(upload_to='blog-authors', verbose_name=_('image'))
    about = models.TextField(verbose_name=_('about'))
    position = models.CharField(max_length=128, verbose_name=_('position'))
    profession = models.CharField(max_length=128, verbose_name=_('profession'))

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('author')
        verbose_name_plural = _('authors')


class BlogCategoryModel(models.Model):
    name = models.CharField(max_length=128)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'


class BlogTagModel(models.Model):
    name = models.CharField(max_length=128)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'tag'
        verbose_name_plural = 'tags'


class BlogModel(models.Model):
    title = models.CharField(max_length=128)
    image = models.ImageField(upload_to='blog-images')
    short_info = models.TextField(null=True)
    content = models.TextField()
    categories = models.ManyToManyField(BlogCategoryModel, related_name='blogs')
    tags = models.ManyToManyField(BlogTagModel, related_name='tags')
    author = models.ForeignKey(AuthorModel, on_delete=models.CASCADE, related_name='blogs')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'blog'
        verbose_name_plural = 'blogs'

blogs/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, DetailView

from blogs.models import BlogModel, BlogCategoryModel, BlogTagModel


class BlogListView(ListView):
    template_name = 'blogs/blog-list.html'
    context_object_name = 'blogs'
    model = BlogModel
    paginate_by = 2

    def get_context_data(self, *, object_list=None, **kwargs):
        blogs = BlogModel.objects.all()
        context = super().get_context_data(object_list=object_list, **kwargs)
        cat = self.request.GET.get('cat')
        if cat:
            blogs = blogs.filter(categories=cat)
        context.update({
            'blogs': blogs,
            'categories': BlogCategoryModel.objects.all(),
            'tags': BlogTagModel.objects.all(),
            'famous_blogs': BlogModel.objects.all().order_by('-created_at')[:2]
        })
        return context


class BlogDetailView(DetailView):
    template_name = 'blogs/blog-detail.html'
    context_object_name = 'blog'
    model = BlogModel

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context.update({
            'blogs': BlogModel.objects.get(pk=self.kwargs['pk']),
            'categories': BlogCategoryModel.objects.all(),
            'tags': BlogTagModel.objects.all(),
            'famous_blogs': BlogModel.objects.all().order_by('-created_at')[:2]
        })
        return context

templates/blogs/blog-filter.html
{% load static %}
<div class="sidebar-3 sidebar-collection col-lg-3 col-md-3 col-sm-4">

                                        <!-- category -->
                                        <div class="sidebar-block">
                                            <div class="title-block">Categories</div>
                                            <div class="block-content">
                                                {% for cat in categories %}
                                                <div class="cateTitle hasSubCategory open level1">
                                                    <a class="cateItem" href="?cat={{ cat.id }}">{{ cat.name }}</a>
                                                </div>
                                                {% endfor %}
                                            </div>
                                        </div>

                                        <!-- recent posts -->
                                        <div class="sidebar-block">
                                            <div class="title-block">Recent Posts</div>
                                            <div class="post-item-content">
                                                {% for blog in famous_blogs %}
                                                <div>
                                                    <div class="late-item first-child">
                                                        <a href="{% url 'blogs:detail' pk=blog.id %}">
                                                            <p class="content-title">{{ blog.title }}</p>
                                                        </a>
                                                        <span>
                                                            <i class="zmdi zmdi-comments"></i>13 comment
                                                        </span>
                                                        <span>
                                                            <i class="zmdi zmdi-calendar-note"></i>{{ blog.created_at }}
                                                        </span>
                                                        <p class="description">{{ blog.short_info }}
                                                        </p>
                                                        <p class="remove">
                                                            <a href="{% url 'blogs:detail' pk=blog.id %}">READ MORE</a>
                                                        </p>
                                                    </div>
                                                </div>
                                                {% endfor %}
                                            </div>
                                        </div>

                                        <!-- product tag -->
                                        <div class="sidebar-block product-tags">
                                            <div class="title-block">
                                                Blog Tags
                                            </div>
                                            <div class="block-content">
                                                <ul class="listSidebarBlog list-unstyled">
                                                    {% for tag in tags %}
                                                    <li>
                                                        <a href="#" title="Show products matching tag Hot Trend">{{ tag.name }}</a>
                                                    </li>
                                                    {% endfor %}
                                                </ul>
                                            </div>
                                        </div>

                                        <!-- advertising -->
                                        <div class="sidebar-block group-image-special">
                                            <div class="effect">
                                                <a href="#">
                                                    <img class="img-fluid" src="{% static 'img/blog/advertising.jpg' %}" alt="banner-2" title="banner-2">
                                                </a>
                                            </div>
                                        </div>

                                    </div>

templates/blogs/blog-list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="main-content">
        <div id="wrapper-site">
            <div id="content-wrapper">
                <div id="main">
                    <div class="page-home">

                        <!-- breadcrumb -->
                        <nav class="breadcrumb-bg">
                            <div class="container no-index">
                                <div class="breadcrumb">
                                    <ol>
                                        <li>
                                            <a href="#">
                                                <span>Home</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#">
                                                <span>Living Room</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#">
                                                <span>Sofa</span>
                                            </a>
                                        </li>
                                    </ol>
                                </div>
                            </div>
                        </nav>
                        <div class="container">
                            <div class="content">
                                <div class="row">
                                    {% include 'blogs/blog-filter.html' %}
                                    <div class="col-sm-8 col-lg-9 col-md-9 flex-xs-first main-blogs">
                                        <h2>Recent Posts</h2>
                                        {% for blog in blogs %}
                                        <div class="list-content row">
                                            <div class="hover-after col-md-5 col-xs-12">
                                                <a href="{% url 'blogs:detail' pk=blog.id %}">
                                                    <img src="{{ blog.image.url }}" alt="img">
                                                </a>
                                            </div>
                                            <div class="late-item col-md-7 col-xs-12">
                                                <p class="content-title">
                                                    <a href="{% url 'blogs:detail' pk=blog.id %}">{{ blog.title }}</a>
                                                </p>
                                                <p class="post-info">
                                                    <span>{{ blog.created_at }}</span>
                                                    <span>113 Comments</span>
                                                    <span>{{ blog.author.name }}</span>
                                                </p>
                                                <p class="description">{{ blog.short_info }}
                                                </p>
                                                <span class="view-more">
                                                    <a href="{% url 'blogs:detail' pk=blog.id %}">view more</a>
                                                </span>
                                            </div>
                                        </div>
                                        {% endfor %}
                                        <div class="page-list col">
                                            <ul class="justify-content-center d-flex">
                                                {% if page_obj.has_previous %}
                                                <li>
                                                    <a rel="prev" href="?page={{ page_obj.previous_page_number }}" class="previous disabled js-search-link">
                                                        Previous
                                                    </a>
                                                </li>
                                                {% endif %}
                                                {% for page in page_obj.paginator.page_range %}
                                                <li {% if forloop.counter == 1%}class="current active" {% endif %}>
                                                    <a rel="nofollow" href="#" class="disabled js-search-link">
                                                        {{ page }}
                                                    </a>
                                                </li>
                                                {% endfor %}
                                                {% if page_obj.has_next %}
                                                <li>
                                                    <a rel="nofollow" href="?page= {{ page_obj.next_page_number }}" class="disabled js-search-link">
                                                        Next
                                                    </a>
                                                </li>
                                                {% endif %}
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}