conf/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
    path('blogs/', include('blogs.urls', namespace='blogs')),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pages/urls.py
from django.urls import path

from pages.views import HomePageView, ContactTemplateView

app_name = 'pages'

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('contact/', ContactTemplateView.as_view(), name='contact'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]><html class="ie ie9" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!-->
<!--<![endif]-->
<html lang="en">


<!-- blog-list-sidebar-left10:09-->
<head>
    <!-- Basic Page Needs -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Furnitica - Minimalist Furniture HTML Template</title>

    <meta name="keywords" content="Furniture, Decor, Interior">
    <meta name="description" content="Furnitica - Minimalist Furniture HTML Template">
    <meta name="author" content="tivatheme">


    <!-- Mobile Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,500,600,700" rel="stylesheet">

    <!-- Vendor CSS -->
    <link rel="stylesheet" href="{% static 'libs/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'libs/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'libs/nivo-slider/css/nivo-slider.css' %}">
    <link rel="stylesheet" href="{% static 'libs/nivo-slider/css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'libs/nivo-slider/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'libs/font-material/css/material-design-iconic-font.min.css' %}">
    <link rel="stylesheet" href="{% static 'libs/slider-range/css/jslider.css' %}">
    <link rel="stylesheet" href="{% static 'libs/owl-carousel/assets/owl.carousel.min.css' %}">

    <!-- Template CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/reponsive.css' %}">
</head>

<body
        {% if '/blogs/' == request.path %}
            id="blog-list-sidebar-left" class="blog"
        {% elif '/products/' == request.path %}
            id="product-sidebar-left" class="product-grid-sidebar-left"
        {% elif 'contact' in request.path %}
            id="contact" class="Blog"
        {% elif 'blogs/detail/' in request.path %}
            id="blog-detail" class="blog"
        {% elif 'products/detail/' in request.path %}
            id="product-detail"
        {% elif '/users/account/' == request.path %}
            class="user-acount"
        {% elif '/users/wishlist/' == request.path %}
            class="user-wishlist blog"
        {% elif '/users/checkout/' == request.path %}
            class="product-checkout checkout-cart"
        {% elif '/users/register/' == request.path %}
            class="user-register blog"
        {% elif '/users/verify/email/' == request.path %}
            class="user-register blog"
        {% elif '/users/login/' == request.path %}
            class="user-login blog"
        {% elif '/users/reset/password/' == request.path %}
            class="user-reset-password blog"
        {% elif '/users/cart/' == request.path %}
            class="product-cart checkout-cart blog"
        {% endif %}
>
    {% include 'layouts/header-base.html' %}
    <!-- main content -->
    {% block content %}
    {% endblock %}

    <!-- footer -->
    {% include 'layouts/footer.html' %}

    <!-- back top top -->
    <div class="back-to-top">
        <a href="#">
            <i class="fa fa-long-arrow-up"></i>
        </a>
    </div>

    <!-- menu mobie left -->
    {% include 'layouts/menu-mobile-left.html' %}

    <!-- menu mobie right -->
    {% include 'layouts/menu-mobile-right.html' %}

    <!-- Page Loader -->
    <div id="page-preloader">
        <div class="page-loading">
            <div class="dot"></div>
            <div class="dot"></div>
            <div class="dot"></div>
            <div class="dot"></div>
            <div class="dot"></div>
        </div>
    </div>

    <!-- Vendor JS -->
    <script src="{% static 'libs/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'libs/popper/popper.min.js' %}"></script>
    <script src="{% static 'libs/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'libs/nivo-slider/js/jquery.nivo.slider.js' %}"></script>
    <script src="{% static 'libs/owl-carousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'libs/slider-range/js/tmpl.js' %}"></script>
    <script src="{% static 'libs/slider-range/js/jquery.dependClass-0.1.js' %}"></script>
    <script src="{% static 'libs/slider-range/js/draggable-0.1.js' %}"></script>
    <script src="{% static 'libs/slider-range/js/jquery.slider.js' %}"></script>

    <!-- Template JS -->
    <script src="{% static 'js/theme.js' %}"></script>
</body>


<!-- blog-list-sidebar-left10:30-->
</html>

templates/contact.html
{% extends 'base.html' %}
{% load static  %}
{% block content %}
    <div class="main-content">
        <div id="wrapper-site">
            <div id="content-wrapper">

                <!-- breadcrumb -->
                <nav class="breadcrumb-bg">
                    <div class="container no-index">
                        <div class="breadcrumb">
                            <ol>
                                <li>
                                    <a href="#">
                                        <span>Home</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <span>Contact</span>
                                    </a>
                                </li>
                            </ol>
                        </div>
                    </div>
                </nav>
                <div id="main">
                    <div class="page-home">
                        <div class="container">
                            <h1 class="text-center title-page">Contact Us</h1>
                            <div class="row-inhert">
                                <div class="header-contact">
                                    <div class="row">
                                        <div class="col-xs-12 col-sm-4 col-md-4">
                                            <div class="item d-flex">
                                                <div class="item-left">
                                                    <div class="icon">
                                                        <i class="zmdi zmdi-email"></i>
                                                    </div>
                                                </div>
                                                <div class="item-right d-flex">
                                                    <div class="title">Email:</div>
                                                    <div class="contact-content">
                                                        <a href="mailto:support@domain.com">support@domain.com</a>
                                                        <br>
                                                        <a href="mailto:contact@domain.com">contact@domain.com</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-xs-12 col-sm-4 col-md-4">
                                            <div class="item d-flex">
                                                <div class="item-left">
                                                    <div class="icon">
                                                        <i class="zmdi zmdi-home"></i>
                                                    </div>
                                                </div>
                                                <div class="item-right d-flex">
                                                    <div class="title">Address:</div>
                                                    <div class="contact-content">
                                                        23 Suspendis matti, Visaosang Building
                                                        <br>District, NY Accums, North American
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-xs-12 col-sm-4 col-md-4">
                                            <div class="item d-flex justify-content-end  last">
                                                <div class="item-left">
                                                    <div class="icon">
                                                        <i class="zmdi zmdi-phone"></i>
                                                    </div>
                                                </div>
                                                <div class="item-right d-flex">
                                                    <div class="title">Hotline:</div>
                                                    <div class="contact-content">
                                                        0123-456-78910
                                                        <br>0987-654-32100
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="contact-map">
                                    <div id="map">
                                        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3724.3785754726428!2d105.78134315594316!3d21.01753304734255!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x313454ab43c0c4db%3A0xdb6effebd6991106!2sKeangnam+Hanoi+Landmark+Tower!5e0!3m2!1svi!2s!4v1530175498947" allowfullscreen></iframe>
                                    </div>
                                </div>
                                <div class="input-contact">
                                    <p class="text-intro text-center">“Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin, lorem quis bibendum
                                        auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit. Duis sed odio sit
                                        amet nibh vultate cursus a sit amet mauris. Proin gravida nibh vel velit auctor aliquet.”
                                    </p>

                                    <p class="icon text-center">
                                        <a href="#">
                                            <img src="{% static 'img/other/contact_mess.png' %}" alt="img">
                                        </a>
                                    </p>

                                    <div class="d-flex justify-content-center">
                                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                                            <div class="contact-form">
                                                <form action="{% url 'pages:contact' %}" method="post" enctype="multipart/form-data">
                                                    {% csrf_token %}
                                                    <div class="form-fields">
                                                        <div class="form-group row">
                                                            <div class="col-md-6">
                                                                <input class="form-control" name="name" placeholder="Your name">
                                                            </div>
                                                            <div class="col-md-6 margin-bottom-mobie">
                                                                <input class="form-control" name="email" type="email" value="" placeholder="Your email">
                                                            </div>
                                                        </div>
                                                        <div class="form-group row">
                                                            <div class="col-md-12 margin-bottom-mobie">
                                                                <input class="form-control" name="subject" type="text" value="" placeholder="Subject">
                                                            </div>
                                                        </div>
                                                        <div class="form-group row">
                                                            <div class="col-md-12">
                                                                <textarea class="form-control" name="message" placeholder="Message" rows="8"></textarea>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div>
                                                        <button class="btn" type="submit" name="submitMessage">
                                                            <img class="img-fl" src="{% static 'img/other/contact_email.png' %}" alt="img">Send message
                                                        </button>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}